[package]
name = "tealeaves"
version = "0.1.0"
authors = ["Peter Lyons <pete@peterlyons.com>"]

[dependencies]
yasna = "0.1.3"
clap = "2.27.1"               # A simple to use, efficient, and full featured  Command Line Argument Parser 