[package]
name = "tealeaves"
version = "0.2.0"
authors = ["Peter Lyons <pete@peterlyons.com>"]

[dependencies]
base64 = "0.6.0"
byteorder = "1.1.0"
clap = "2.27.1"
hex = "0.3.1"
pem = "0.4"
rsfs = "0.4.1"
