[package]
name = "tealeaves"
version = "0.2.0"
authors = ["Peter Lyons <pete@peterlyons.com>"]

[dependencies]
base64 = "0.6.0"
byteorder = "1.1.0"
clap = "2.27.1"
hex = "0.3.1"
nom = "3.2.1"
# nom_pem = "1.0.2"
nom_pem = { path = "../nom_pem" }
rsfs = "0.4.1"
yasna = "0.1.3"
